config/routes.rb
Rails.application.routes.draw do
#This says that the messages'resources are apart of the conversation
  # resources :conversations do
  #   resources :messages, only: [:create]
  # end

  resources :callback_links

  resources :users do
    scope module: :users do
      resource :nfused_page, only: [:create, :destroy, :show]
    end
    # post to this new controller.
    resources :nfuse_pages
    # resources :conversations
    resources :shouts
    # resources :comments do
    #   resources :comments
    # end
    member do
      get :following, :followers, :bio, :feed, 
      :settings, :explore, :explore_users, :nfuse_page, 
      :vue, :followed_pages, :user_likes
    end
  end
  resources :comments do
    resources :comments
  end

  resources :pages, except: :index do
    resources :comments
  end
    get 'all_pages', to: 'pages#index', as: 'all_pages'
  
  get 'show_forum', to: "pages#show_forum"
  post 'nfuse_post/:id', to: 'shouts#nfuse_post', as: 'nfuse_post'

  # on line 27 of routes file replace that block with this.
  scope module: :shouts do
    # This was breaking the * routes 
    #  Any character after shout/<c> it thinks is an id.
    scope '/nfuse_shouts' do
      post "like", to: "likes#create",       as: :like_shout
      delete "dislike", to: "likes#destroy", as: :dislike_shout
    end
  end
  scope module: :comments do

    post "like", to: "like_comments#create",       as: :like_this_comment
    delete "dislike", to: "like_comments#destroy", as: :dislike_this_comment
  end

  get 'individual_post', to: 'pages#individual_post'

  resources :shouts do
    resources :comments
  end

  resources :nfuse_pages do
    resources :shouts
  end

  scope '/comments' do
    post '/twitter/:twitter_post_id',     to: 'comments#create'
    post '/instagram/:instagram_post_id', to: 'comments#create'
    post '/facebook/:facebook_post_id',   to: 'comments#create'
    post '/youtube/:youtube_post_id',     to: 'comments#create'
    post '/gplus/:gplus_post_id',         to: 'comments#create'
    post '/vimeo/:vimeo_post_id',         to: 'comments#create'
    post '/pinterest/:pinterest_post_id',       to: 'comments#create'
    post '/tumblr/:tumblr_post_id',       to: 'comments#create'

    # Add others follow convention

  end

  # resources :events do
  #   resources :comments
  #   member do
  #     put "like",    to: "events#like"
  #     put "dislike", to: "events#dislike"
  #   end
  # end
  
  resources :contacts, path: 'contact_us', only: [:create]
  get 'contact_us', to: 'contacts#new'
  resources :sessions,                  only: [:new, :create, :destroy]
  resources :relationships,             only: [:create, :destroy]
  resources :password_resets
  get 'password_reset', to: 'password_resets#new'
  resources :activities, path: 'notifications'
  get 'activities/individual_activity'
  # Authentication and Settings
  get '/signup',       to: 'users#new'
  get '/login',        to: 'sessions#new', as: :signin
  # get '/auth/facebook/callback' , to: 'sessions#fb_callback', as: :fb_signup
  get '/signout',      to: 'sessions#destroy'
  get '/settings',     to: 'users#settings'
  get '/destroytoken', to: 'users#destroytoken'
  get '/destroyuser',  to: 'users#destroyuser'
  get '/remove_token',  to: 'users#remove_token'
  #get    '/nfuse_page', to: 'users#nfuse_page'
  
  # New Hub and hub all pages

  get '/nfusers',     to: 'pages#nfuse_user_posts'
  get 'explore_posts', to: 'pages#explore_posts'
  # get '/hub/hq/pages',       to: 'pages#nfuse_page_posts'
  # get '/hub/hq/nfuse',       to: 'pages#nfuse_posts'

  get '/twitter_news',     to: 'pages#twitter_news'
  get '/viral_youtube',    to: 'pages#viral_youtube'
  get '/youtube_music',    to: 'pages#youtube_music'
  get '/youtube_trailers', to: 'pages#youtube_trailers'

  # Static pages
  get '/help',              to: 'pages#help'
  # get '/about',             to: 'pages#about'
  get '/privacy',           to: 'pages#privacy'
  get '/preview',           to: 'shouts#preview'

  get '/contacts', to: 'contacts#new'

  get '/feed_content', to: 'users#feed_content', as: :feed_content
  get '/search', to: 'searches#searchcontent'
  get '/random_search', to: 'searches#random_search'

  #  OmniAuth * Registrations
  # if user.id.present?
   scope '/auth' do
     get '/instagram/callback',     to: 'registrations/instagram#create'
     get '/twitter/callback',       to: 'registrations/twitter#create'
     get '/failure',                to: 'registrations/twitter#failure'
     get '/facebook/callback',      to: 'registrations/facebook#create'
     get '/google_oauth2/callback', to: 'registrations/youtube#create'
     get '/gplus/callback',         to: 'registrations/gplus#create'
     get '/vimeo/callback',         to: 'registrations/vimeo#create'
     get '/pinterest/callback',     to: 'registrations/pinterest#create'
     get '/tumblr/callback',        to: 'registrations/tumblr#create'
   end
  # else
  #   get 'auth/:provider/callback', to: 'sessions#create'
  # end
  # Likes
  # post '/twitter/favorite/:tweet_id', to: 'likes#twitter'
  # post '/twitter/retweet/:tweet_id',  to: 'shares#twitter'
  # post '/instagram/like/:media_id',   to: 'likes#instagram'
  # post '/facebook/like/:post_id',     to: 'likes#facebook'

  root to: 'pages#home'

  #COMPANIES
  get'/my_top_50', to: 'pages#mytop50'
  get'/most_popular', to: 'pages#mostpopular'
  get'/random', to: 'pages#random'
  get'/trending', to: 'pages#trending'
  get '/businessconnector', to: 'pages#business_connector'

  #CELEBRITIES
  get'/celebrities', to: 'pages#celebrity_connector'
  #TVSHOWS
  get 'tv_shows', to: 'pages#tv_show_connector'
  ######## SPORTS
  get 'sports', to: 'pages#sports_connector'
  ######MUSIC
  get 'music', to: 'pages#music_connector'
  ####FOOD
  get 'food', to: 'pages#food_connector'
  #####TRAVEL
  get 'travel', to: 'pages#travel_connector'
  #####FASHION
  get 'fashion', to: 'pages#fashion_connector'
  #####YOUTUBERS
  get 'youtubers', to: 'pages#youtubers'

  #####YOUTUBERS
  get 'news', to: 'pages#news_connector'
  #####YOUTUBERS
  get 'fitness', to: 'pages#fitness_connector'
  #####YOUTUBERS
  get 'nerdish', to: 'pages#nerdish_connector'
  #####YOUTUBERS
  get 'shopping', to: 'pages#shopping_connector'
  #####YOUTUBERS
  get 'wedding', to: 'pages#wedding_connector'
  #####YOUTUBERS
  get 'animals', to: 'pages#animals_connector'
  #####YOUTUBERS
  get 'instagramers', to: 'pages#instagramers_connector'
  get 'sitemap.xml', :to => 'sitemaps#index', :defaults => {:format => 'xml'}
end
 # http://stackoverflow.com/questions/25415123/is-there-something-wrong-with-my-current-user/25416296#25416296

app/models/shout.rb
class Shout < ActiveRecord::Base
  include PublicActivity::Model
  tracked only: [:create], owner: ->(controller, model) { controller.current_user }, user_recipients: ->(controller, model) {model && model.user.followers.pluck(:id).join(", ")}
  belongs_to :user 
  # I added is_exclusive to the shouts table and user_recipients to activities
  # now I need to get the ids from a users followers when a user make an exclusive post
  # So. If is_exclusive == true track the action 
  # only exclusive posts need to be tracked
  # This is a create problem. So I need ot turn off P_A if it isn't an exclusive post

  #has_and_belongs_to_many :nfuse_pages
  has_many :nfuse_pages, dependent: :destroy
  validates :user_id, :content, presence: true
  has_many :comments, :as => :commentable, dependent: :destroy
  acts_as_votable

  attr_accessor :photo_delete, :video_delete

  has_destroyable_file :pic, :snip, :video

  has_attached_file :pic, 
                    :styles => { 
                      :thumb => "600",
                      :medium => "300",
                      :small => "160"
                    }

  validates_attachment_content_type :pic,
                                    :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif" ]

  has_attached_file :video,  
                    styles: {
                            medium: { :geometry => "640x480#", :format => 'flv' },
                             thumb: { :geometry => "100x100#", :format => 'jpg', time: 10 }
                         }, processors: [:ffmpeg]

    has_attached_file :snip, :styles => {
      :medium => { :geometry => "640x480", :format => 'flv' },
      :thumb => { :geometry => "100x100#", :format => 'jpg', :time => 10 }
    }, :processors => [:transcoder]
  # This was my bad.
  # * http://stackoverflow.com/questions/22926614/rails-4-model-is-valid-but-wont-save
  check_file_types = ->(record) {
                  true if (record.is_pic            = !!(record.pic_content_type))
                  true if (record.is_video          = !!(record.snip_file_name))
                  true if (record.is_full_video     = !!(record.video_file_name))
                  true if (record.is_link           = !!(record.url))
                  !!(record.content                 = record.content)
  }

  before_create { |record| check_file_types.call(record) }
  
  def all_votes
   ActsAsVotable::Vote.where(votable_id: self.id)
  end

  auto_html_for :url do
    html_escape
    image
    youtube(:width => '100%', :height => 225, :autoplay => false)
    vimeo(:width => '100%', :height => 225, :autoplay => false)
    soundcloud
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

  # def self.my_nfuses(nfuse_page_id)
  #   self.where(nfuse_page_id: nfuse_page_id)
  # end
  
  # def self.nfuse_page_owner(nfuse_page_user_id)
  #   User.find_by id: nfuse_page_user_id
  # end

  # def reshout_post(sid, uid, oid)
  #  nf_page = NfusePage.new(shout_id: sid, user_id: uid, owner_id: oid)
  #  nf_page.save
  # end

 end

app/controllers/shouts/likes_controller.rb
class Shouts::LikesController < ApplicationController

  respond_to :json, :js, :html

  def create
    unless ActsAsVotable::Vote.find_by(voter_id:   current_user.id,
                                       owner_id:   params[:owner_id],
                                       owner_type: params[:owner_type],
                                       votable_id: params[:id])
      send( params.fetch(:key, :basic).to_sym ) # Object.send
    end
    @shout = {
        id: params[:id],
        like_score: ActsAsVotable::Vote.where(votable_id: params[:id]).size,
        owner_id: params[:owner_id],
        owner_type: params[:owner_type],
        provider: params[:key] || 'nfuse'
    }
    # TODO Turn off PA when a user likes their own thing
    if current_user.id != params[:owner_id].to_i && @shout[:owner_type] != 'Page'
    current_user.create_activity(key: 'shout.like',
                                 parameters: {id:       @shout[:id],
                                              provider: @shout[:provider]},
                                 owner: current_user,
                                 recipient: User.find(@shout[:owner_id]))# unless options[:owner]['id'] == options[:recipient]['id']
    end
    respond_to do |format|
      format.js { render file: 'shouts/like.js.erb'} #'alert("like")' and return
    end
  end

  def destroy
    @shout = {
        id: params[:id],
        like_score: ActsAsVotable::Vote.where(votable_id: params[:id]).size,
        owner_id: params[:owner_id],
        provider: params[:key]
    }
    @like = ActsAsVotable::Vote.find_by(voter_id: current_user.id, votable_id: params[:id])
    @like.destroy
    # activity = PublicActivity::Activity.find_by_trackable_id_and_trackable_type(params['id'], 'User')
    # activity.destroy if activity.present?
    respond_to do |format|
      format.js { render file: 'shouts/dislike.js.erb'} #'alert("like")' and returnR
    end
  end

  private

  def basic
    ActsAsVotable::Vote.create(vote_params)
  end# Ruby magick

  def nfuse
    ActsAsVotable::Vote.create(vote_params)
  end# Ruby magick


  def twitter
    Twitter::Vote.create(vote_params) 
    # Networks::Vote.create(vote_params) 
  end

  def facebook
    Facebook::Vote.create(vote_params)
    # Networks::Vote.create(vote_params) 
  end

  def instagram
    Instagram::Vote.create(vote_params) 
    # Networks::Vote.create(vote_params) 
  end

  def google_oauth2
    Youtube::Vote.create(vote_params)
    # Networks::Vote.create(vote_params) 
  end

  def vimeo
    Vimeo::Vote.create(vote_params) 
    # Networks::Vote.create(vote_params) 
  end

  def pinterest
    Pinterest::Vote.create(vote_params)
  end

  def gplus
    Gplus::Vote.create(vote_params) 
    # Networks::Vote.create(vote_params) 
  end

  def tumblr
    Tumblr::Vote.create(vote_params) 
    # Networks::Vote.create(vote_params) 
  end

  def vote_params
   {votable_id: params[:id],
      voter_id: current_user.id,
      owner_id: params[:owner_id],
      owner_type: params[:owner_type]}
  end

end
# attrs = {id: params[:id], provider: params[:key]}

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
  before_action :set_shout, only: [:show, :edit, :update, :destroy]
  respond_to :json, :js, :html

  def show
    @commentable = set_shout
    @comments = @commentable.comments
    @comment = Comment.new

    respond_to do |format|
       format.html
       format.json { render json: @shout }
    end

  end

  def new
    @shout = Shout.new
  end

  def edit
  end

  def create
    if params[:shout]["is_exclusive"] == "0"
      Shout.public_activity_off
    end
    @shout = current_user.shouts.create(shout_params)
    respond_to do |format|
      if @shout.save
          format.html { redirect_to feed_user_path(@shout.user)}
          format.json { render json: @shout, status: :created, location: @shout }
      else
          format.html { redirect_to new_shout_path }
          format.json { render json: @shout.errors, status: :unprocessable_entity }
      end
    end
  end

  def preview
    @shout = Shout.new(url: params['url'])
    render :text => @shout.url_html
  end

  def update
    if @shout.update_attributes(shout_params)
      redirect_to @shout
    else
      render :edit
    end
  end

  def destroy
    @shout.destroy
    redirect_to feed_user_path(@shout.user)
  end

  def nfuse_post
    if @nfuse_page == NfusePage.find_by(social_id: params[:id], social_key: params[:key])
      render json: { nfuse_page: @nfuse_page }
    else
      @nfuse_page = NfusePage.build(params)
      render json: { nfuse_page: @nfuse_page }
    end
  end


  def my_nfuses
    @nfuses = current_user.nfuse_post
    @nfuses.each do |b|
      @shouts = Shout.my_nfuses(b.id)
    end
  end

  private
    def set_shout
      @shout = Shout.find(params[:id])
    end

  def shout_params
      params.require(:shout).permit( :user_id, :content, :pic, :snip, :is_video, :link, :is_link, :is_pic, :url, :url_html, :is_full_video, :video, :is_exclusive )
    end

    def correct_user
      @shout = current_user.shouts.find_by(id: params[:id])
      redirect_to feed_user_path(@user) if @shout.nil?
    end

end

app/helpers/shouts/likes_helper.rb
module Shouts::LikesHelper
end

app/helpers/shouts_helper.rb
module ShoutsHelper
end

app/views/shouts/_nfuse_post.html.erb
<% @shouts.each do |shout| %>
	<div class="visible-md visible-lg individual_post item nfuse_post ">
	  <% if !shout.url.blank? %>
	    <p> <%= shout.url_html %></p>
	  <% else shout.is_pic? %>
	    <p class="timeline-user-box">
	      <%= image_tag shout.pic.url(:medium) %>
	    </p>
	  <% end %>
  </div>
<% end %>

app/views/shouts/_shout.html.erb
<!-- *Start* Views/shouts/_shout.html -->
<style type="text/css">
  .post-padding{
    margin-top: 1vh;
  }

  h2 {
    color: #fff;
  }

.section-bottom-button{
  padding-top: 16px;
}
</style>

<script type='text/javascript'>
function load(request) {
  $('#code').text(request);
  $('#preview').html(request);
}

function preview(value) {
  console.log("preview; value = " + value);

  /*
  $.getJSON("/preview?callback=?", value, function(data){
    load(data);
    console.log("preview callback\n" + data);
  });
  */

  $.ajax({
    dataType: "html",
    url: "/preview?url=" + value['url']
  })
  .done( function(data){
    load(data);
    console.log("preview callback\n" + data);
  });
}

function previewUrl() {
  preview({'url':$('#url_body').val()});
}

$('#examples a').click(function() {
  $('#url_body').focus(); 
  $('#url_body').val( $(this).attr('href'));
  previewUrl();
});

$(function () { 
  $("#url_body").focus();
  previewUrl();
});

//$('#upload_form').delayedObserver(1, function(element, value) { previewUrl() });
//$('#url_body').keydown(function() { alert("hi"); previewUrl() });
//$('#url_body').bind('input propertychange', function() { alert("hi"); previewUrl() });  


</script>
<div class="Alignthisorelse">
  <div class="container post-padding">
    <div class="col-sm-8 col-sm-offset-2 form-box wow fadeInUp">
      <div class="form-top-new-post">
        <div class="form-top-left">
          <h2><strong>Create A Post<strong></h2>
            <p>Share a picture or url</p>
        </div>
        <div class="form-top-right">
          <a href="#"><%= image_tag("postlightgray.fw.png", size: "65x65") %></a>
        </div>
      </div>
      <div class="form-bottom">

      <%= form_for @shout, :html => { :multipart => true, id: "upload_form", role:"form" } do |f| %>
        <% if @shout.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@shout.errors.count, "error") %> prohibited this post from being saved:</h2>
            <ul>
            <% @shout.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="Alignthisorelse">
          <div class="container">

              <div class="row">
                <div class="col-sm-3 how-it-works-box wow fadeInUp">
                    <div class="how-it-works-box-icon">
                      <a href="#"><%= image_tag("circlephoto.fw.png", size: "160x160") %></a>
                    </div>
                    <div class="fileUpload btn-link-1">
                      <span>Upload Pic</span>
                       <%= f.file_field :pic, id: 'pictureInput', placeholder: "Pic", type: "file", class: "upload"  %>
                    </div>
                </div>

                <div class="col-sm-3 col-sm-offset-1 how-it-works-box wow fadeInDown">
                  <div class="how-it-works-box-icon">
                    <a href="#"><%= image_tag("circlein2darkgray.fw.png", size: "160x160") %></a>
                  </div>
                  <div class="form-grouP">
                    <%= f.text_area :url, id: 'url_body', class: "form-control", placeholder: "URL of everything", onChange: 'previewUrl()', type:"search" %>
                  </div>
                </div>
               </div>
<!--                 <div class="row">
                 <div class="col-sm-3 how-it-works-box wow fadeInUp">
                   <div class="how-it-works-box-icon">
                     <a href="#"><%#= image_tag("circlevideo.fw.png", size: "160x160") %></a>
                   </div>
                   <div class="fileUpload btn-link-1">
                     <span>Upload Video</span>
                     <%#= f.file_field :video, id: 'pictureInput2', placeholder: "Snip", type: "file", class: "upload" %>
                   </div>
                 </div>

                 <div class="col-sm-3 col-sm-offset-1 how-it-works-box wow fadeInDown">
                   <div class="how-it-works-box-icon">
                     <%#= image_tag("circlesnipdarkgray.fw.png", size: "160x160") %>
                   </div>
                   <div class="fileUpload btn-link-1">
                     <span>Upload Snip</span>
                       <%#= f.file_field :snip, id: 'pictureInput2', placeholder: "Snip", type: "file", class: "upload" %>
                   </div>
                 </div>
              </div> -->

              <div class="row">
                <div class="col-sm-5 col-sm-offset-1 section-bottom-button wow fadeInUp">
                  <div id="target"></div>
                  <div id="target2"></div>
                  <div id="preview"></div>
                  <%= f.text_area :content, class: "form-control", placeholder: "Write a description for your post...", type:"search" %>
                </div>
              </div>
              <div class="row">
                <%= f.label "Do you want to send this to only your followers?" %>
                <%= f.check_box :is_exclusive %>
              </div>
              <div class="row">
                <div class="col-sm-4 section-bottom-button wow fadeInUp">
                  <button type="submit" class="btn">
                   Post!
                  </button>
                </div>
              </div>

          </div>
        </div>

      <% end %>
      </div>
    </div>
  </div>
</div>







<script>
  $(function() {
    $('#pictureInput').on('change', function(event) {
      var files = event.target.files;
      var image = files[0]
      var reader = new FileReader();
      reader.onload = function(file) {
        var img = new Image();
        console.log(file);
        img.src = file.target.result;
        $('#target').html(img);
      }
      reader.readAsDataURL(image);
      console.log(files);
    });
  });
</script>
<script>
  $(function() {
    $('#pictureInput2').on('change', function(event) {
      var files = event.target.files;
      var image = files[0]
      var reader = new FileReader();
      reader.onload = function(file) {
        var img = new Video();
        console.log(file);
        img.src = file.target.result;
        $('#target2').html(img);
      }
      reader.readAsDataURL(image);
      console.log(files);
    });
  });
</script>

app/views/shouts/dislike.js.erb
//$("#shout").html("<%#= escape_javascript(render('users/follow')) %>")
//$("#shout-<%= @shout[:id]%>").text('<%=@shout[:like_score] %>');
$('span.liked-<%= @shout[:id] %>').html(parseInt($('span.liked-<%= @shout[:id] %>').html(), 10)-1)

app/views/shouts/like.js.erb
//$("#follow_form").html("<%#= escape_javascript(render('shouts/like')) %>")
// $("#shout-<%= @shout[:id]%>").text('<%=@shout[:like_score] %>');
$('span.liked-<%= @shout[:id] %>').html(parseInt($('span.liked-<%= @shout[:id] %>').html(), 10)+1)

app/views/shouts/new.html.erb
<!-- *Start* Views/shouts/new.html -->

<%= render 'shout' %> <!-- Fetching defined Embedded Ruby post rules-->

<!-- *End* Views/shouts/new.html -->

app/views/shouts/show.html.erb
<!-- *Start* Views/shouts/show.html -->
<div class="visible-md visible-lg container_profile">

  <div class="post_main">
    <ul class="post_header">
	    <li></li><%= image_tag @shout.user.avatar(:small), class: 'user' %>
			<li></li><%= link_to @shout.user.full_name, feed_user_path(@shout.user) %>
			<li></li><%= image_tag "filter-nfuse2.png", size: "50x50" %>
		</ul>
	</div><br>

	<% if @shout.url.blank? %>
		<p><%= @shout.url_html %></p>

	<% else @shout.pic? %>
		<p class="user-box">
		  <%= image_tag @shout.pic.url if @shout.pic.exists? %>
		  <%= @shout.content %>
		</p>
	<% end %>

  <div class="<%= @shout.class %>-<%= @shout.id %>">
	  <%= link_to "Like", like_shout_path(@shout), method: :post %><%= @shout.like_score %> | 
	  <%= link_to "Dislike", dislike_shout_path(@shout), method: :delete %><%= @shout.dislike_score %>
	  <%#= link_to pluralize(@comments.count, 'comment'), @shout, class: 'comments' %>
	</div>
	<!--<div>
		<div><%#= render "comments/comments" %></div>
		<div><%#= render "comments/form" %></div>
	</div>-->
</div>
<!-- *End* Views/shouts/show.html -->