config/routes.rb
Rails.application.routes.draw do
#This says that the messages'resources are apart of the conversation
  # resources :conversations do
  #   resources :messages, only: [:create]
  # end

  resources :callback_links

  resources :users do
    scope module: :users do
      resource :nfused_page, only: [:create, :destroy, :show]
    end
    # post to this new controller.
    resources :nfuse_pages
    # resources :conversations
    resources :shouts
    # resources :comments do
    #   resources :comments
    # end
    member do
      get :following, :followers, :bio, :feed, 
      :settings, :explore, :explore_users, :nfuse_page, 
      :vue, :followed_pages, :user_likes
    end
  end
  resources :comments do
    resources :comments
  end

  resources :pages, except: :index do
    resources :comments
  end
    get 'all_pages', to: 'pages#index', as: 'all_pages'
  
  get 'show_forum', to: "pages#show_forum"
  post 'nfuse_post/:id', to: 'shouts#nfuse_post', as: 'nfuse_post'

  # on line 27 of routes file replace that block with this.
  scope module: :shouts do
    # This was breaking the * routes 
    #  Any character after shout/<c> it thinks is an id.
    scope '/nfuse_shouts' do
      post "like", to: "likes#create",       as: :like_shout
      delete "dislike", to: "likes#destroy", as: :dislike_shout
    end
  end
  scope module: :comments do

    post "like", to: "like_comments#create",       as: :like_this_comment
    delete "dislike", to: "like_comments#destroy", as: :dislike_this_comment
  end

  get 'individual_post', to: 'pages#individual_post'

  resources :shouts do
    resources :comments
  end

  resources :nfuse_pages do
    resources :shouts
  end

  scope '/comments' do
    post '/twitter/:twitter_post_id',     to: 'comments#create'
    post '/instagram/:instagram_post_id', to: 'comments#create'
    post '/facebook/:facebook_post_id',   to: 'comments#create'
    post '/youtube/:youtube_post_id',     to: 'comments#create'
    post '/gplus/:gplus_post_id',         to: 'comments#create'
    post '/vimeo/:vimeo_post_id',         to: 'comments#create'
    post '/pinterest/:pinterest_post_id',       to: 'comments#create'
    post '/tumblr/:tumblr_post_id',       to: 'comments#create'

    # Add others follow convention

  end

  # resources :events do
  #   resources :comments
  #   member do
  #     put "like",    to: "events#like"
  #     put "dislike", to: "events#dislike"
  #   end
  # end
  
  resources :contacts, path: 'contact_us', only: [:create]
  get 'contact_us', to: 'contacts#new'
  resources :sessions,                  only: [:new, :create, :destroy]
  resources :relationships,             only: [:create, :destroy]
  resources :password_resets
  get 'password_reset', to: 'password_resets#new'
  resources :activities, path: 'notifications'
  get 'activities/individual_activity'
  # Authentication and Settings
  get '/signup',       to: 'users#new'
  get '/login',        to: 'sessions#new', as: :signin
  # get '/auth/facebook/callback' , to: 'sessions#fb_callback', as: :fb_signup
  get '/signout',      to: 'sessions#destroy'
  get '/settings',     to: 'users#settings'
  get '/destroytoken', to: 'users#destroytoken'
  get '/destroyuser',  to: 'users#destroyuser'
  get '/remove_token',  to: 'users#remove_token'
  #get    '/nfuse_page', to: 'users#nfuse_page'
  
  # New Hub and hub all pages

  get '/nfusers',     to: 'pages#nfuse_user_posts'
  get 'explore_posts', to: 'pages#explore_posts'
  # get '/hub/hq/pages',       to: 'pages#nfuse_page_posts'
  # get '/hub/hq/nfuse',       to: 'pages#nfuse_posts'

  get '/twitter_news',     to: 'pages#twitter_news'
  get '/viral_youtube',    to: 'pages#viral_youtube'
  get '/youtube_music',    to: 'pages#youtube_music'
  get '/youtube_trailers', to: 'pages#youtube_trailers'

  # Static pages
  get '/help',              to: 'pages#help'
  # get '/about',             to: 'pages#about'
  get '/privacy',           to: 'pages#privacy'
  get '/preview',           to: 'shouts#preview'

  get '/contacts', to: 'contacts#new'

  get '/feed_content', to: 'users#feed_content', as: :feed_content
  get '/search', to: 'searches#searchcontent'
  get '/random_search', to: 'searches#random_search'

  #  OmniAuth * Registrations
  # if user.id.present?
   scope '/auth' do
     get '/instagram/callback',     to: 'registrations/instagram#create'
     get '/twitter/callback',       to: 'registrations/twitter#create'
     get '/failure',                to: 'registrations/twitter#failure'
     get '/facebook/callback',      to: 'registrations/facebook#create'
     get '/google_oauth2/callback', to: 'registrations/youtube#create'
     get '/gplus/callback',         to: 'registrations/gplus#create'
     get '/vimeo/callback',         to: 'registrations/vimeo#create'
     get '/pinterest/callback',     to: 'registrations/pinterest#create'
     get '/tumblr/callback',        to: 'registrations/tumblr#create'
   end
  # else
  #   get 'auth/:provider/callback', to: 'sessions#create'
  # end
  # Likes
  # post '/twitter/favorite/:tweet_id', to: 'likes#twitter'
  # post '/twitter/retweet/:tweet_id',  to: 'shares#twitter'
  # post '/instagram/like/:media_id',   to: 'likes#instagram'
  # post '/facebook/like/:post_id',     to: 'likes#facebook'

  root to: 'pages#home'

  #COMPANIES
  get'/my_top_50', to: 'pages#mytop50'
  get'/most_popular', to: 'pages#mostpopular'
  get'/random', to: 'pages#random'
  get'/trending', to: 'pages#trending'
  get '/businessconnector', to: 'pages#business_connector'

  #CELEBRITIES
  get'/celebrities', to: 'pages#celebrity_connector'
  #TVSHOWS
  get 'tv_shows', to: 'pages#tv_show_connector'
  ######## SPORTS
  get 'sports', to: 'pages#sports_connector'
  ######MUSIC
  get 'music', to: 'pages#music_connector'
  ####FOOD
  get 'food', to: 'pages#food_connector'
  #####TRAVEL
  get 'travel', to: 'pages#travel_connector'
  #####FASHION
  get 'fashion', to: 'pages#fashion_connector'
  #####YOUTUBERS
  get 'youtubers', to: 'pages#youtubers'

  #####YOUTUBERS
  get 'news', to: 'pages#news_connector'
  #####YOUTUBERS
  get 'fitness', to: 'pages#fitness_connector'
  #####YOUTUBERS
  get 'nerdish', to: 'pages#nerdish_connector'
  #####YOUTUBERS
  get 'shopping', to: 'pages#shopping_connector'
  #####YOUTUBERS
  get 'wedding', to: 'pages#wedding_connector'
  #####YOUTUBERS
  get 'animals', to: 'pages#animals_connector'
  #####YOUTUBERS
  get 'instagramers', to: 'pages#instagramers_connector'
  get 'sitemap.xml', :to => 'sitemaps#index', :defaults => {:format => 'xml'}
end
 # http://stackoverflow.com/questions/25415123/is-there-something-wrong-with-my-current-user/25416296#25416296

app/models/concerns/shared/callbacks.rb
module Shared::Callbacks
  extend ActiveSupport::Concern

  included do
    before_destroy :remove_activity
  end

  def remove_activity
    activity = PublicActivity::Activity.find_by_trackable_id_and_trackable_type(self.id, self.class.to_s)
    activity.destroy if activity.present?
    true
  end
end

app/views/shared/_comment.html.erb
<li class="left clearfix">
  <span class="chat-img pull-left">
    <%= link_to image_tag(comment.user.avatar(:small), class: "user_profile_picture"), feed_user_path(comment.user) %>
  </span>
  <div class="chat-body clearfix">
    <div>
      <strong class="primary-font">
        <%= comment.user.user_name %>
      </strong> 
<!--       <small class="pull-right text-muted">
        <span class="glyphicon glyphicon-time"></span>12 mins ago
      </small> -->
    </div>
      <p>
        <%= comment.body %>
      </p>
  </div>
</li>

app/views/shared/_comment_form.html.erb
<%= form_tag(shout.form_path , method: :post, remote: true) do %>
  <div class="input-group">
  	<%= text_field_tag 'comment[body]', nil, id: "btn-input", class: "form-control input-sm", placeholder: "Comment here..." %>
  	<%= hidden_field_tag 'comment[user_id]', current_user.id  %>
    <span class="input-group-btn">
    	<%= submit_tag "Comment", class: "btn btn-info btn-sm", id: "btn-comment" %>
    </span>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<!-- *Start* Views/shared/_error_messages.html -->
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<!-- *End* Views/shared/_error_messages.html -->

app/views/shared/_nfuse_page.html.erb
<div id="masonJar" class="center hub_container clearfix masonJar">
  <% @nfuse_pages.each do |shout| %>
      <%#= shout.inspect %>
      <% if !shout.url.blank? %>
        <div class="individual_post faved_post item" id="content-box-feed">
          <p> 
            <%= shout.url_html %>
          </p>
        </div>
      <% else shout.is_pic? %>
        <% if params[:social_key] == "youtube" %>
        <div class="individual_post faved_post item" id="content-box-feed">
          <video 
            id="ytplayer" 
            type="text/html" 
            width="100%" 
            height="225" 
            src="https://www.youtube.com/embed/<%= shout.url %>" 
            frameborder="0">
          </video>
        </div>
        <% else %>
        <div class="individual_post faved_post item" id="content-box-feed">
          <p class="timeline-user-box">
            <%= image_tag shout.url %>
          </p>
        </div>
        <% end %>
      <% end %>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<!-- *Start* Views/shared/_stats.html -->
<% @user ||= current_user %>
<div class="stats">
  <ul class="profile_nav_links">
    <li><%= link_to "Feed", feed_user_path(@user) %></li>
    <li><%= link_to "Vue", vue_user_path(@user) %></li>
    <!-- <li><%#= link_to "Nfused", nfuse_page_user_path(@user) %></li> -->
    <li><%= link_to "Following: #{@user.relationships.where(follow_type: 'User').collect(&:id).count}", following_user_path(@user) %></li>
    <li><%= link_to "Followers: #{@user.followers.count}", followers_user_path(@user) %></li>
    <li class="total_like_counter"> Likes: <%= @user.total_likes %></li>
  </ul>
</div>
<!-- *End* Views/shared/_stats.html -->

app/views/shared/_user_info.html.erb
<!-- *Start* Views/shared/_user_info.html -->
<a href="<%= user_path(current_user) %>">
  <%= avatar_for current_user %>
</a>
<h1>
  <%= current_user.full_name %>
</h1>
<h6><%= link_to user.user_name, feed_user_path(user) %></h6>
<span>
  <%= link_to "view my profile", feed_user_path(params[:id]) %>
</span>
<!-- *End* Views/shared/_user_info.html -->