config/routes.rb
Rails.application.routes.draw do
#This says that the messages'resources are apart of the conversation
  # resources :conversations do
  #   resources :messages, only: [:create]
  # end

  resources :callback_links

  resources :users do
    scope module: :users do
      resource :nfused_page, only: [:create, :destroy, :show]
    end
    # post to this new controller.
    resources :nfuse_pages
    # resources :conversations
    resources :shouts
    # resources :comments do
    #   resources :comments
    # end
    member do
      get :following, :followers, :bio, :feed, 
      :settings, :explore, :explore_users, :nfuse_page, 
      :vue, :followed_pages, :user_likes
    end
  end
  resources :comments do
    resources :comments
  end

  resources :pages, except: :index do
    resources :comments
  end
    get 'all_pages', to: 'pages#index', as: 'all_pages'
  
  get 'show_forum', to: "pages#show_forum"
  post 'nfuse_post/:id', to: 'shouts#nfuse_post', as: 'nfuse_post'

  # on line 27 of routes file replace that block with this.
  scope module: :shouts do
    # This was breaking the * routes 
    #  Any character after shout/<c> it thinks is an id.
    scope '/nfuse_shouts' do
      post "like", to: "likes#create",       as: :like_shout
      delete "dislike", to: "likes#destroy", as: :dislike_shout
    end
  end
  scope module: :comments do

    post "like", to: "like_comments#create",       as: :like_this_comment
    delete "dislike", to: "like_comments#destroy", as: :dislike_this_comment
  end

  get 'individual_post', to: 'pages#individual_post'

  resources :shouts do
    resources :comments
  end

  resources :nfuse_pages do
    resources :shouts
  end

  scope '/comments' do
    post '/twitter/:twitter_post_id',     to: 'comments#create'
    post '/instagram/:instagram_post_id', to: 'comments#create'
    post '/facebook/:facebook_post_id',   to: 'comments#create'
    post '/youtube/:youtube_post_id',     to: 'comments#create'
    post '/gplus/:gplus_post_id',         to: 'comments#create'
    post '/vimeo/:vimeo_post_id',         to: 'comments#create'
    post '/pinterest/:pinterest_post_id',       to: 'comments#create'
    post '/tumblr/:tumblr_post_id',       to: 'comments#create'

    # Add others follow convention

  end

  # resources :events do
  #   resources :comments
  #   member do
  #     put "like",    to: "events#like"
  #     put "dislike", to: "events#dislike"
  #   end
  # end
  
  resources :contacts, path: 'contact_us', only: [:create]
  get 'contact_us', to: 'contacts#new'
  resources :sessions,                  only: [:new, :create, :destroy]
  resources :relationships,             only: [:create, :destroy]
  resources :password_resets
  get 'password_reset', to: 'password_resets#new'
  resources :activities, path: 'notifications'
  get 'activities/individual_activity'
  # Authentication and Settings
  get '/signup',       to: 'users#new'
  get '/login',        to: 'sessions#new', as: :signin
  # get '/auth/facebook/callback' , to: 'sessions#fb_callback', as: :fb_signup
  get '/signout',      to: 'sessions#destroy'
  get '/settings',     to: 'users#settings'
  get '/destroytoken', to: 'users#destroytoken'
  get '/destroyuser',  to: 'users#destroyuser'
  get '/remove_token',  to: 'users#remove_token'
  #get    '/nfuse_page', to: 'users#nfuse_page'
  
  # New Hub and hub all pages

  get '/nfusers',     to: 'pages#nfuse_user_posts'
  get 'explore_posts', to: 'pages#explore_posts'
  # get '/hub/hq/pages',       to: 'pages#nfuse_page_posts'
  # get '/hub/hq/nfuse',       to: 'pages#nfuse_posts'

  get '/twitter_news',     to: 'pages#twitter_news'
  get '/viral_youtube',    to: 'pages#viral_youtube'
  get '/youtube_music',    to: 'pages#youtube_music'
  get '/youtube_trailers', to: 'pages#youtube_trailers'

  # Static pages
  get '/help',              to: 'pages#help'
  # get '/about',             to: 'pages#about'
  get '/privacy',           to: 'pages#privacy'
  get '/preview',           to: 'shouts#preview'

  get '/contacts', to: 'contacts#new'

  get '/feed_content', to: 'users#feed_content', as: :feed_content
  get '/search', to: 'searches#searchcontent'
  get '/random_search', to: 'searches#random_search'

  #  OmniAuth * Registrations
  # if user.id.present?
   scope '/auth' do
     get '/instagram/callback',     to: 'registrations/instagram#create'
     get '/twitter/callback',       to: 'registrations/twitter#create'
     get '/failure',                to: 'registrations/twitter#failure'
     get '/facebook/callback',      to: 'registrations/facebook#create'
     get '/google_oauth2/callback', to: 'registrations/youtube#create'
     get '/gplus/callback',         to: 'registrations/gplus#create'
     get '/vimeo/callback',         to: 'registrations/vimeo#create'
     get '/pinterest/callback',     to: 'registrations/pinterest#create'
     get '/tumblr/callback',        to: 'registrations/tumblr#create'
   end
  # else
  #   get 'auth/:provider/callback', to: 'sessions#create'
  # end
  # Likes
  # post '/twitter/favorite/:tweet_id', to: 'likes#twitter'
  # post '/twitter/retweet/:tweet_id',  to: 'shares#twitter'
  # post '/instagram/like/:media_id',   to: 'likes#instagram'
  # post '/facebook/like/:post_id',     to: 'likes#facebook'

  root to: 'pages#home'

  #COMPANIES
  get'/my_top_50', to: 'pages#mytop50'
  get'/most_popular', to: 'pages#mostpopular'
  get'/random', to: 'pages#random'
  get'/trending', to: 'pages#trending'
  get '/businessconnector', to: 'pages#business_connector'

  #CELEBRITIES
  get'/celebrities', to: 'pages#celebrity_connector'
  #TVSHOWS
  get 'tv_shows', to: 'pages#tv_show_connector'
  ######## SPORTS
  get 'sports', to: 'pages#sports_connector'
  ######MUSIC
  get 'music', to: 'pages#music_connector'
  ####FOOD
  get 'food', to: 'pages#food_connector'
  #####TRAVEL
  get 'travel', to: 'pages#travel_connector'
  #####FASHION
  get 'fashion', to: 'pages#fashion_connector'
  #####YOUTUBERS
  get 'youtubers', to: 'pages#youtubers'

  #####YOUTUBERS
  get 'news', to: 'pages#news_connector'
  #####YOUTUBERS
  get 'fitness', to: 'pages#fitness_connector'
  #####YOUTUBERS
  get 'nerdish', to: 'pages#nerdish_connector'
  #####YOUTUBERS
  get 'shopping', to: 'pages#shopping_connector'
  #####YOUTUBERS
  get 'wedding', to: 'pages#wedding_connector'
  #####YOUTUBERS
  get 'animals', to: 'pages#animals_connector'
  #####YOUTUBERS
  get 'instagramers', to: 'pages#instagramers_connector'
  get 'sitemap.xml', :to => 'sitemaps#index', :defaults => {:format => 'xml'}
end
 # http://stackoverflow.com/questions/25415123/is-there-something-wrong-with-my-current-user/25416296#25416296

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	# activity_count = current_user.activity_count

	def index
		activity1 = PublicActivity::Activity.includes(:recipient, :owner, :trackable).where(recipient_id: current_user.id, recipient_type: 'User')

		activity2 = PublicActivity::Activity.includes(:owner, :trackable).where("user_recipients LIKE ':id,%' or user_recipients LIKE '%, :id' or user_recipients LIKE '%, :id,%' or user_recipients = ':id'", id: current_user.id)

		total_activities = (activity1 + activity2).sort_by{|t| - t.created_at.to_i}
		if params[:page]
			@activities = get_page_and_offset(11, params[:page].to_i, total_activities)
		else
			@activities = get_page_and_offset(11, 1, total_activities)
		end

		respond_to do |format|
			format.js
		end
	end

	def get_page_and_offset(per_page, page = 1, activities)
		total = activities.length
		if total > 0
			if per_page >= total # 10 or 11
				result = activities.first(total)
				params[:last_page] = page
				return result
			elsif per_page < total # 23

				if ( page * per_page ) < total # 2 * 11 < 23
					if page == 1
						result = activities[0..(per_page - 1)]
						params[:first_page] = page
						return result
					else
						offset_by = ( page - 1 ) * per_page # 1 * 11
						next_page = (page * per_page) - 1
						result = activities[offset_by..next_page]
						params[:middle_page] = page
						return result
					end
				elsif ( page * per_page ) >= total # 3 * 11 > 23
					offset_by = ( page - 1 ) * per_page
					to_end = total - 1
					result = activities[offset_by..to_end]
					params[:last_page] = page
					return result
				else
					# Noting more to do
				end

			else
				# Nothing more to do
			end
		else
			# Do Nothing
		end
	end

	def individual_activity
		@activity = PublicActivity::Activity.find(params[:shout])
		respond_to do |format|
			format.js
		end
	end
end
# Regex to match serialized values in between quotes
#   /(["'])((?:(?!\1)[^\\]|(?:\\\\)*\\[^\\])*)\1/

# Example: 
# string = "{:id=>\"1187467057945665_1072558892769816\", :provider=>\"facebook\"}"
# regex = /(["'])((?:(?!\1)[^\\]|(?:\\\\)*\\[^\\])*)\1/
# string.scan(regex)
# => [["\"", "1187467057945665_1072558892769816"], ["\"", "facebook"]]

# post_id = string.scan(regex)[0][1]
# provider = string.scan(regex)[1][1]

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
  <% @activities.each do |activity| %>
    <% case activity.trackable_type %>
    <% when 'Relationship' %>
      <% if activity.owner.nil? %>
      <% else %>
        <div class="row notification followed">
          <div class="col-xs-1 user-img">
            <% if activity.owner.avatar_file_name.present? && activity.owner.avatar_file_name.include?('graph.facebook.com') %>
              <%= link_to image_tag(activity.owner.avatar_file_name, title: "#{ activity.owner.first_name}"), feed_user_path(activity.owner) %>
            <% else %>
              <%= link_to image_tag(activity.owner.avatar(:small), title: "#{ activity.owner.first_name}"), feed_user_path(activity.owner) %>
            <% end %>
            <!-- <img src="/assets/users/brunomars.jpg" alt="User Image"/> -->
          </div>
          <div class="col-xs-10 notification-body">
            <p>
              <%= link_to activity.owner.first_name.capitalize, feed_user_path(activity.owner), class: 'user-link' %>
              followed you! 
              <span class="timer">
                <%= time_ago_in_words(activity.created_at) %> 
              </span></p>
          </div>
          <div class="col-xs-1 notification-action">
            <a><i class="fa"></i></a>
          </div>
        </div>
      <% end %>
    <% when 'Comment' %>
      <% if activity.owner.nil? %>
      <% else %>
       <%# @post_entry = Notification::Timeline.new(activity.parameters[:id], activity.parameters[:provider], activity.recipient ).construct unless nil? %>
        <div class="row notification form_post_action">
          <div class="col-xs-1 user-img">
            <% if activity.owner.avatar_file_name.present? && activity.owner.avatar_file_name.include?('graph.facebook.com') %>
              <%= link_to image_tag(activity.owner.avatar_file_name, title: "#{ activity.owner.first_name}"), feed_user_path(activity.owner) %>
            <% else %>
             <%= link_to image_tag(activity.owner.avatar(:small), title: "#{ activity.owner.first_name}"), feed_user_path(activity.owner) %>
            <% end %>
          </div>
          <div class="col-xs-10 notification-body">
            <% if activity.key == 'comment.tagged' %>
              <% comment_type = Comment.find(activity.trackable_id) %>
              <p>
                <%= link_to activity.owner.first_name.capitalize, feed_user_path(activity.owner), class: 'user-link' %> 
                <% if comment_type.parent.nil? %>
                  taggged you in a forum post!
                <% else %>
                  tagged you in a forum comment!
                <% end %>
                <span class="timer">
                  <%= time_ago_in_words(activity.created_at) %>
                </span>
              </p>
            <% elsif activity.key == 'comment.like' %>
              <p>
                <%= link_to activity.owner.first_name.capitalize, feed_user_path(activity.owner), class: 'user-link' %>
                liked your forum comment!
              <span class="timer">
                <%= time_ago_in_words(activity.created_at) %>
              </span>
              </p>
            <% elsif activity.key == 'comment.new_comment' %>
              <p>
                <%= link_to activity.owner.first_name.capitalize, feed_user_path(activity.owner), class: 'user-link' %>
                commented your forum post!
              <span class="timer">
                <%= time_ago_in_words(activity.created_at) %>
              </span>
              </p>
            <% else %>
              <p>
                <%= link_to activity.owner.first_name.capitalize, feed_user_path(activity.owner), class: 'user-link' %> 
                liked your forum post!
                <span class="timer">
                  <%= time_ago_in_words(activity.created_at) %>
                </span>
              </p>
            <% end %>
          </div>
          <div class="col-xs-1 notification-action">
            <a><i class="fa"></i></a>
          </div>
        </div>
      <% end %>
    <% when 'User' %>
      <% if activity.owner.nil? %>
      <% else %>
       <%# @post_entry = Notification::Timeline.new(activity.parameters[:id], activity.parameters[:provider], activity.recipient ).construct unless nil? %>
        <div class="row notification post_was_liked">
          <div class="col-xs-1 user-img">
              <% if activity.owner.avatar_file_name.present? && activity.owner.avatar_file_name.include?('graph.facebook.com') %>
                <%= link_to image_tag(activity.owner.avatar_file_name, title: "#{ activity.owner.first_name}"), feed_user_path(activity.owner) %>
              <% else %>
               <%= link_to image_tag(activity.owner.avatar(:small), title: "#{ activity.owner.first_name}"), feed_user_path(activity.owner) %>
              <% end %>
          </div>
          <div class="col-xs-10 notification-body">
            <p>
              <%= link_to activity.owner.first_name.capitalize, feed_user_path(activity.owner), class: 'user-link' %> 
              liked your post! 
              <span class="timer">
                <%= time_ago_in_words(activity.created_at) %>
              </span>
            </p>
          </div>
          <div class="col-xs-1 notification-action">
            <a><i class="fa"></i></a>
          </div>
        </div>
      <% end %>
    <% when 'Shout' %>
      <% if activity.owner.nil? %>
      <% else %>
      <% end %>
        <div class="row notification exclusive">
          <div class="col-xs-1 user-img">
            <% if activity.owner.avatar_file_name.present? && activity.owner.avatar_file_name.include?('graph.facebook.com') %>
              <%= link_to image_tag(activity.owner.avatar_file_name, title: "#{ activity.owner.first_name}"), feed_user_path(activity.owner) %>
            <% else %>
              <%= link_to image_tag(activity.owner.avatar(:small), title: "#{ activity.owner.first_name}"), feed_user_path(activity.owner) %>
            <% end %>
          </div>
          <div class="col-xs-10 notification-body">
            <p><%= link_to activity.owner.first_name.capitalize, feed_user_path(activity.owner, class: 'user-link') %> 
              send you an exclusive post!
              <span class="timer">
                <%= time_ago_in_words(activity.created_at) %> 
              </span>
            </p>
          </div>
          <button type="button" class="col-xs-1 notification-action" data-toggle="modal" data-target="#exclusivemodal">
            <%= link_to activities_individual_activity_path(params: {shout: activity.id}), remote: true do %>
              <i class="fa"></i>
            <% end %>
           <!--  <a href="#"><i class="fa"></i></a> -->
          </button>
        </div>
    <% else %>
    <% end %>
  <% end %>

app/views/activities/_facebook_entry.html.erb
<% begin %>
  <% case @post_entry.type %>
  <% when nil %>
    <div class="timeline-user-box">
      <%= image_tag(@post_entry.image, class: 'facebook_image') %>
    </div>
    <div class="center">
      <% if @post_entry.name.present? %>
        <%= @post_entry.name %>
      <%elsif @post_entry.message.present? %>
        <%= truncate(@post_entry.message, lenght: 30) %>
      <%end%>
    </div>
  <% when 'link' %>
    <% if @post_entry.image.present? %>
      <div class="timeline-user-box">
        <%= image_tag(@post_entry.image, class: 'facebook_image') %>
      </div>
    <%end%>
    <div class="center">
      <% if @post_entry.description.present? %>
        <%= truncate(@post_entry.description, lenght: 30) %>
      <%end%>
    </div>
    <div class="center">
      <% if @post_entry.message.present? %>
        <%= truncate(@post_entry.message, lenght: 30)%>
      <%end%>
    </div>
  <% when 'video' %>
    <div class="center">
      <% if @post_entry.text == 'youtube.com' || @post_entry.source.include?('youtube') %>
        <iframe
        id="ytplayer"
        width="100%"
        autoplay=0
        src="<%= @post_entry.youtube_source %>"
        frameborder="0"
        allowfullscreen>
        </iframe>
        <div class="center">
          <% if @post_entry.message.present? %>
            <%= truncate(@post_entry.message, lenght: 30) %>
          <%end%>
        </div>
      <%else%>
        <video controls preload="none" poster=<%= @post_entry.image %> >
          <source src="<%= @post_entry.source %>" type='video/mp4' />
          <source src="<%= @post_entry.source %>" type='video/ogv' />
        </video>
        <div class="center">
          <% if @post_entry.message.present? %>
            <%= truncate(@post_entry.message, lenght: 30) %>
          <%end%>
        </div>
      <%end%>
    </div>
  <% when 'status' %>
    <div class="center text_only_post">
      <% if @post_entry.message.present? %>
        <%= truncate(@post_entry.message, lenght: 30) %>
      <%end%>
    </div>
  <% end %>
<% rescue %>
  <div class='center text_only_post'>
    <% if @post_entry.message.present? %>
      <%= truncate(@post_entry.message, lenght: 30) %>
    <%end%>
  </div>
<% end %>

app/views/activities/_gplus_entry.html.erb
<% case @post_entry.type %>
<% when 'photo' %>
  <div class="timeline-user-box">
    <%= image_tag(@post_entry.image, :class => "gplus_image") %>
  </div>
  <% if @post_entry.text.present? %>
    <div class="center">
      <%= truncate(@post_entry.text, lenght: 30) %>
    </div>
  <% end %>
<% when 'video' %>
  <div class="timeline-user-box">
    <iframe
    id="ytplayer"
    type="text/html"
    width="100%"
    height="225"
    src="<%= @post_entry.video %>"
    frameborder="0"
    allowfullscreen>
    </iframe>
  </div>
  <% if @post_entry.text.present? %>
    <div class="center">
      <%= truncate(@post_entry.text, lenght: 30) %>
    </div>
  <% end %>
<% else %>
  <div class="center text_only_post">
    <%= truncate(@post_entry.text, lenght: 30) %>
  </div>
<% end %>

app/views/activities/_individual.html.erb
<!-- EXCLUSIVE POST MODAL -->
<article class="individual_post item instagram_post0">
  <header class="post_header">
    <div class="user">
      <% if activity.owner.avatar_file_name.present? && activity.owner.avatar_file_name.include?('graph.facebook.com') %>
        <%= link_to image_tag(activity.owner.avatar_file_name, class: "user_profile_picture", size: '45', title: "#{ activity.owner.first_name}"), feed_user_path(activity.owner) %>
      <% else %>
        <%= link_to image_tag(activity.owner.avatar(:small), class: "user_profile_picture", size: '45', title: "#{ activity.owner.first_name}"), feed_user_path(activity.owner) %>
      <% end %>
      <%= link_to activity.owner.first_name.capitalize, feed_user_path(activity.owner) %>
    </div>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <a class="timeStamp" href="#" target="_blank" title="Go To Entry">
      <i class="fa"></i> <%= time_ago_in_words(activity.created_at) %>
    </a>
  </header>
  <main class="post_content">
    <% if !activity.trackable.url.blank? %>
      <p> <%= activity.trackable.url_html %></p>
    <% elsif activity.trackable.is_pic? %>
      <div class="timeline-user-box image_post">
        <%= image_tag activity.trackable.pic.url %>
           </div>
    <% elsif activity.trackable.is_video? %>
      <div class="timeline-user-box">
        <video 
          preload="none"
          id="ytplayer" 
          type="video/mp4" 
          width="100%" 
          height="225" 
          src="<%= activity.trackable.video_url %>" 
          frameborder="0"
          allowfullscreen
          controls>
        </video>
      </div>
    <% elsif activity.trackable.is_full_video? %>
      <div class="timeline-user-box">
        <video 
          preload="none"
          autoload="none"
          type="video/flv" 
          width="100%" 
          src="<%= activity.trackable.full_video_url %>" 
          frameborder="0"
          allowfullscreen
          controls>
        </video>
           </div>
    <% end %>
    <% if activity.trackable.content.present? %>
      <p>
        <%= activity.trackable.content %>
      </p>
    <% end %>
  </main>
<!--   <footer class="post_actions">
    <a class="likePost" data-method="post" data-remote="true" href="#" rel="nofollow">
      <i class="fa"></i><span>666</span>
    </a>
  </footer> -->
</article>

app/views/activities/_instagram_entry.html.erb
<div class="timeline-user-box">
  <% if @post_entry.type == "image" %>
    <%= image_tag(@post_entry.image, :class => "image_post") %>
  <% elsif @post_entry.type == "video" %>
    <video controls autoload="none" style="background:transparent url(<%= @post_entry.image %>) no-repeat 50% 50%;" >
      <source src="<%= @post_entry.video %>" type='video/mp4' />
      <source src="<%= @post_entry.video %>" type='video/ogv' />
    </video>
  <% end %>
</div>
<% if @post_entry.text.present? %>
  <div class='center'>
    <%= @post_entry.text %>
  </div>
<% end %>

app/views/activities/_nfuse_entry.html.erb
<% if !@post_entry.url.blank? %>
  <div class='timeline-user-box center style="iframe{width:100%;}'>
    <%= @post_entry.url_html %>
  </div>
  <div class="center">
    <%= truncate(@post_entry.content, lenght: 30) %>
  </div>
<% elsif @post_entry.is_pic? %>
  <div class="timeline-user-box image_post">
    <%= image_tag @post_entry.pic_url %>
  </div>
  <div class="center">
      <%= truncate(@post_entry.content, lenght: 30) %>
  </div>
<% elsif @post_entry.is_video? %>
  <div class="timeline-user-box">
    <video 
      style="background:transparent url(<%= @post_entry.pic_url %>) no-repeat 50% 50%;"
      preload="none"
      id="ytplayer" 
      type="video/mp4" 
      width="100%" 
      height="225" 
      src="<%= @post_entry.video_url %>" 
      frameborder="0"
      allowfullscreen
      controls>
    </video>
  </div>
  <div class="center">
    <%= truncate(@post_entry.content, lenght: 30) %>
  </div>
<% elsif @post_entry.is_full_video? %>
  <div class="timeline-user-box">
    <video 
      preload="none"
      id="ytplayer" 
      type="video/flv" 
      width="100%" 
      height="225" 
      src="<%= @post_entry.full_video_url %>" 
      frameborder="0"
      allowfullscreen
      controls>
    </video>
  </div>
  <div class="center">
    <%= truncate(@post_entry.content, lenght: 30) %>
  </div>
<% else %>
  <div class="center text_only_post ">
    <%= truncate(@post_entry.content, lenght: 30) %>
  </div>
<% end %>

app/views/activities/_pinterest_entry.html.erb
<% if @post_entry.type == "image" %>
  <div class="timeline-user-box">
    <%= image_tag(@post_entry.image, :class => "image_@post_entry") %>
  </div>
  <% if @post_entry.text.present? %>
    <div class="center">
      <%= @post_entry.text %>
    </div>
  <% end %>
<% elsif @post_entry.type == "video" %>
  <div class="timeline-user-box">
    <iframe
        id="ytplayer"
        width="100%"
        autoplay=0
        src="<%= @post_entry.video %>"
        frameborder="0"
        allowfullscreen>
    </iframe>
  </div>
  <% if @post_entry.text.present? %>
    <div class="center">
      <%= @post_entry.text %>
    </div>
  <% end %>
<% end %>

app/views/activities/_tumblr_entry.html.erb
<% if @post_entry.type == 'photo'%>
  <div class="timeline-user-box">
    <%= image_tag(@post_entry.image, :class => "tumblr_image") %>
  </div>
  <% if @post_entry.text.present? %>
    <div class="center">
      <%= truncate(strip_tags(@post_entry.text), lenght: 30)%>
    </div>
  <% end %>
<% elsif @post_entry.type == 'video' %>
  <% if @post_entry.video_type == 'tumblr' %>
    <div class="timeline-user-box">
      <video controls autoload="none" style="background:transparent url(<%= @post_entry.video_thumbnail %>) no-repeat 50% 50%;" >
        <source src="<%= @post_entry.video %>" type='video/mp4' />
        <source src="<%= @post_entry.video %>" type='video/ogv' />
      </video>
    </div>
  <% else %>
    <div class="timeline-user-box">
      <iframe
      id="ytplayer"
      type="text/html"
      width="100%"
      height="225"
      src="<%= @post_entry.video %>"
      frameborder="0"
      allowfullscreen>
      </iframe>
    </div>
  <% end %>
  <% if @post_entry.text.present? %>
    <div class="center">
      <%= truncate(strip_tags(@post_entry.text), lenght: 30) %>
    </div>
  <% end %>
<% elsif @post_entry.type == 'audio' %>
  <div class="timeline-user-box">
    <Iframe
      <%= @post_entry.audio %>>
    </Iframe>
  </div>
  <% if @post_entry.text.present? %>
    <div class="center">
      <%= truncate(strip_tags(@post_entry.text), lenght: 30)%>
    </div>
  <% end %>
<% elsif @post_entry.type == 'text'  %>
  <div class="center text_only_post">
    <%= @post_entry.body %>
  </div>
<% elsif @post_entry.type == 'quote'  %>
  <div class="center text_only_post">
    <%= truncate(strip_tags(@post_entry.text), lenght: 30) %>
  </div>
<% elsif @post_entry.type == 'link'  %>
  <div class="center">
    <a href="#{@post_entry.link_to_url}">
      <%= @post_entry.excerpt %>
    </a>
    <%= truncate(strip_tags(@post_entry.text), lenght: 30) %>
  </div>
<% else %>
  <div class="center text_only_post">
    <%= truncate(strip_tags(@post_entry.text), lenght: 30) %>
  </div>
<% end %>

app/views/activities/_twitter_entry.html.erb
<% case @post_entry.type %>
<% when 'youtube_video' %>
<div class="timeline-user-box">
  <iframe
  id="ytplayer"
  type="text/html"
  width="100%"
  height="225"
  src="https://www.youtube.com/embed/<%= @post_entry.twitter_url_video %>"
  frameborder="0"
  allowfullscreen>
  </iframe>
</div>
  <div class='center'>
    <%= @post_entry.text %>
  </div>
<% when 'animated_gif', 'video' %>
<div class="timeline-user-box">
  <video controls autoload="none" style="background:transparent url(<%= @post_entry.image %>) no-repeat 50% 50%;" >
    <source src="<%= @post_entry.video %>" type='video/mp4' />
    <source src="<%= @post_entry.video %>" type='video/ogv' />
  </video>
</div>
  <div class='center'>
    <%= @post_entry.text %>
  </div>
<% when 'photo' %>
<div class="timeline-user-box">
  <%= image_tag(@post_entry.image, :class => "image_post") %>
</div>
  <div class='center'>
    <%= @post_entry.text %>
  </div>
<% else %>
  <div class='center text_only_post'>
    <%= @post_entry.text %>
  </div>
<% end %>